config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :projects, only: [:show]
  get "contact_forms", to: "contact_forms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :file, attachment: true

  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "My Contact Form",
      to: "hugorobert.dev@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :projects_technologies, dependent: :destroy
  has_many :technologies, through: :projects_technologies
end

app/models/projects_technology.rb
class ProjectsTechnology < ApplicationRecord
  belongs_to :project
  belongs_to :technology
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def index
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
    @proprojects = Project.where(adjectiv: "pro")
    @persoprojects = Project.where(adjectiv: "perso")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @project = Project.find(params[:id])    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact_forms/index.html.erb
<div class="contact_form_body">
  <h1>Confiez-moi vos idées et besoins.</h1>
  <script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
  <script>
    hbspt.forms.create({
      region: "eu1",
      portalId: "139488037",
      formId: "a86d3510-b6bf-45fa-825f-c8e021faadf5"
    });
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="first-page-container">
  <div class="photo-hugo">
    <div class="photo-hugo_peel_off"></div>
  </div>
  <div class="words-hugo">
  <h1>Ensemble, <br> concrétisons vos visions, <br>réussissez vos projets.</h1>
  <h4>Hugo ROBERT</h4>
  </div>
</div>

<div class="projects-page-container">
  <div class="projects-pro-container" id="projects_pro">
    <div class="projects-text" >
      <h2>Projets professionnels</h2>
      <p>Découvrez mon parcours jalonné de projets captivants et enrichissants, où j'ai pu mettre en œuvre mon expertise pour aider mes clients à réaliser leurs ambitions.</p>    </div>
    <div class="projects-cards">
      <% @proprojects.each do |proproject| %>
        <%= link_to "#{project_path(proproject)}#top" do %>
          <div class="<%= proproject.date > Date.current ? 'project-card project-card_futur' : 'project-card' %>">
            <div class="card-firsthalf">
              <h3><%= proproject.name %></h3>
              <p><%= proproject.description %></p>
            </div>
            <div class="card-secondhalf">
              <div class="card-icon">
                <i class="fa-brands fa-github"></i>
              </div>
              <div class="card-photo" style="background-image: url(<%= proproject.photo %>);">
              </div>
              <div class="card-miscelanous">
                <p><%= proproject.date %></p>
                <p><%= proproject.importance %>/<%= @proprojects.count %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="projects-perso-container" id="projects_perso">
    <div class="projects-cards">
      <% @persoprojects.each do |persoproject| %>
        <%= link_to "#{project_path(persoproject)}#top" do %>
          <div class="<%= persoproject.date > Date.current ? 'project-card project-card_futur' : 'project-card' %>">
            <div class="card-firsthalf">
              <h3><%= persoproject.name %></h3>
              <p><%= persoproject.description %></p>
            </div>
            <div class="card-secondhalf">
              <div class="card-icon">
                <i class="fa-brands fa-github"></i>
              </div>
              <div class="card-photo" style="background-image: url(<%= persoproject.photo %>);">
              </div>
              <div class="card-miscelanous">
                <p><%= persoproject.date %></p>
                <p><%= persoproject.importance %>/<%= @persoprojects.count %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="projects-text">
      <h2>Projets Personnels</h2>
      <p>Mes projets personnels reflètent mon engagement à développer constamment mes compétences, explorer de nouveaux domaines du code et repousser les limites de ma créativité pour offrir des solutions toujours plus innovantes et efficaces.</p>    </div>
    </div>
  </div>
</div>


<div class="cv-page-container">
  <div class="photo-contacts">
    <div class="photo">
      <%= link_to ("https://youtu.be/vHHCFiA7uEo?t=1650"), target:"_blank" do %>
        <i class="fa-brands fa-youtube"></i>
      <% end %>
    </div>
    <div class="contacts">
      <div class="contacts-icons">
      <%= link_to "https://github.com/Threbor", target:"_blank" do %>
        <i class="fa-brands fa-github"></i>
      <% end %>
      <%= link_to "https://www.linkedin.com/in/hugo-robert-devfullstack", target:"_blank" do %>
        <i class="fa-brands fa-linkedin-in"></i>
      <% end %>
      </div>
      <div class="contacts-text" id="contact_message">
        <%= link_to contact_forms_path, target:"_blanck" do %>
          <h3><i class="fa-solid fa-envelope-open-text"></i> Contactez-moi dès maintenant </h3>
          <p>Discutons rapidement de la manière dont je peux vous aider et bénéficier d'un accompagnement personnalisé.</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="cv">
    <div class="containter_cv">
      <div class="cv-title">
        <h1><I>Curriculum vitæ</I></h1>
        <h2>Hugo ROBERT</h2>
        <h2>Développeur Full-Stack</h2>
        <h2>Ruby on Rails</h2>
      </div>
      <div class="cv-text">
        <h3>Expériences Développeur</h3>
        <h4>Le Wagon</h4>
        <h6>Janvier 2023 - Mars 2023 • 9 semaines • Nantes</h6>
        <ul>
            <li>Maîtrise des langages de programmation tels que Ruby, HTML, CSS et JavaScript</li>
            <li>Développement des applications Swappy et Exceptions en utilisant le framework Rails</li>
            <li>Manipulation et gestion des bases de données avec MySQL et PostgreSQL</li>
            <li>Conception et création de l'application Swappy, une applicaiton pour trouver des activités</li>
            <li>Conception et réalisation du site web Exceptions, un market place</li>
        </ul>
      </div>
      <div class="cv-text">
        <h3>Expériences Juridiques</h3>
        <h4>Appui à l’animation territoriale sur les politiques publiques de l’Etat (en alternance)</h4>
        <h5>Préfecture de Loire-Atlantique - Pole politiques publiques</h5>
        <h6>Oct 2021 - Sep 2022 - 11 mois, Nantes</h6>
        <ul>
          <li>Expertise et conseils juridiques, suivi des politiques publique et soutient à l’organisation.</li>
        </ul>
      </div>
      <div class="cv-text">
        <h4>Chargé de mission, Ressources, Dettes et Trésorerie</h4>
        <h5>Région Normandie - Direction des finances et de l’appui au pilotage</h5>
        <h6>Avr 2021 - Sep 2022 - 6 mois (2 mois en stage 4 en CDD), Rouen</h6>
        <ul>
          <li>Elaboration de plans prévisionnels de trésorerie, suivi des recettes de la Région, préparation budgétaire (2Mds€).</li>
        </ul>
      </div>
      <div class="cv-text">
        <h3>Expériences associatives</h3>
        <h4>Sauveteur en mer (SNSM)</h4>
        <h6>2017 -  2020 - 3 ans</h6>
        <ul>
          <li>Saisons et interventions bénévoles.</li>
        </ul>
      </div>
      <div class="cv-text">
        <h4>Culture off/on, président et co-fondateur</h4>
        <h6>2019 -  2023 - 4 ans</h6>
        <ul>
          <li>Réunions hebdomadaires et débats sur des sujets culturels.</li>
          <li>Récoltes d'expériences personnelles culturelles</li>
        </ul>
      </div>
      <div class="cv-text">
        <h3>Education</h3>
        <h4>Master 2 Droit Public - Droit des Collectivités territoriales (en alternance)</h4>
        <h5>Nantes Université</h5>
        <h6>2021 - 2022, Nantes</h6>
      </div>
      <div class="cv-text">
        <h4>Master 1 Droit Public - Carrières et Management Public</h4>
        <h5>Institut de Préparation à l’Adminstration Générale de Nantes</h5>
        <h6>2020 - 2021, Nantes</h6>
      </div>
        <%= link_to ('https://drive.google.com/file/d/1frmtOlmWkujaIgKt0H1rcj5iASL3InSl/view?usp=sharing'), target:'_blank' do %>
      <div class="icon-download">
          <i class="fa-solid fa-download"></i>
        <p>Télécharger le CV</p>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="banner_project" id="top" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @project.photo %>);">
  <div class="container_project">
  <% case @project.adjectiv %>
  <% when 'pro' %>
    <%= link_to "#{root_path}#projects_pro", class:"banner_project_icon"  do %>
      <i class="fa-solid fa-circle-arrow-left"></i>
    <% end %>
  <% when 'perso' %>
      <%= link_to "#{root_path}#projects_perso", class:"banner_project_icon" do %>
      <i class="fa-solid fa-circle-arrow-left"></i>
    <% end %>
  <% end %>
    <h1><%= @project.name %></h1>
  </div>
</div>

<div class="details_project">
  <div class="links_projects">
    <%= link_to @project.repo_url, target: "_blank" do %>
      <i class="fa-brands fa-github icon_project"></i>
    <% end %>
    <%= link_to @project.app_link, target: "_blank" do %>
      <div class="app_link">
        <p>L'app </p>
      </div>
    <% end %>
  </div>
  <div class="description_enhanced_project">
    <p><%= @project.description_enhanced %></p>
  </div>
  <div class="key_features_project">
    <h2>Les fonctionnalités clés</h2>
    <ul>
      <% @project.key_features.each do |key_feature| %>
        <li><%= key_feature %></li>
      <% end %>
    </ul>
  </div>

  <h2>Les technologies utilisées</h2>
  <div class="cards_tech">
      <% @project.technologies.each do |technology| %>
        <div class="card-category_tech" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=technology.photo%>)">
          <%= technology.name %>
        </div>
      <% end %>
  </div>
</div>